export const C2E_CODE_TYPE = 'sdons:Code';
export const C2E_PERSON_TYPE = 'sdons:Person';
export const C2E_ORGANIZATION_TYPE = 'sdons:Organization';
export const C2E_DIGITAL_DOCUMENT_TYPE = 'sdons:DigitalDocument';
export const C2E_RESOURCE_COLLECTION_ID = 'c2ens:c2eResources';
export const C2E_CONTENT_TYPE_COLLECTION_ID = 'c2ens:c2eContentTypes';
export const C2E_SOURCE_CODE_ID = 'c2ens:c2eSourceCode';
export const C2E_COLLECTION_TYPE = 'sdons:Collection';
export const C2E_DATASET_TYPE = 'sdons:Dataset';
export const C2E_CREATIVE_WORK_TYPE = 'sdons:CreativeWork';
export const C2E_DATA_CATALOG_TYPE = 'sdons:DataCatalog';
export const STRING_TYPE = 'xsd:string'; // https://www.w3.org/TR/xmlschema-2/#string
export const INTEGER_TYPE = 'xsd:integer'; // https://www.w3.org/TR/xmlschema-2/#string
export const BOOLEAN_TYPE = 'xsd:boolean';
export const DECIMAL_TYPE = 'xsd:decimal';
export const FLOAT_TYPE = 'xsd:float';
export const DOUBLE_TYPE = 'xsd:double';
export const DATETIME_TYPE = 'xsd:dateTime';
export const DATE_TYPE = 'xsd:date';
export const TIME_TYPE = 'xsd:time';
export const C2E_ListItem_TYPE = 'sdons:ListItem';
export const C2E_BreadcrumbList_TYPE = 'sdons:BreadcrumbList';
export const C2E_CollectionPage_TYPE = 'sdons:CollectionPage';
